import Link from "next/link";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header style={{ padding: 24, borderBottom: "1px solid #eee" }}>
          <nav style={{ display: "flex", gap: 16, alignItems: "center" }}>
            <Link href="/" style={{ fontWeight: 700 }}>Arman Mukhi</Link>
            <Link href="/projects">Projects</Link>
            <Link href="/posts">Posts</Link>
            <Link href="/achievements">Achievements</Link>
            <Link href="/about">About</Link>
          </nav>
        </header>

        <div style={{ padding: 24 }}>{children}</div>
      </body>
    </html>
  );
}
